[phases.setup]
nixPkgs = ['python310', 'gcc']

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --prefer-binary numpy==1.22.0",
  "pip install --prefer-binary pandas==1.5.3",
  "pip install -r requirements.txt"
]

[phases.start]
cmd = "gunicorn app:app"
