[build]
nixpkgs = ["python310", "gcc"]
shell = """
pip install --upgrade pip
pip install --prefer-binary numpy==1.22.0 pandas==1.5.3
pip install -r requirements.txt
"""

[start]
cmd = "gunicorn app:app"
